#!/usr/bin/env bash
# Install Nginx
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=tLXNDzc-2fA permanent;' /etc/nginx/sites-available/default
service nginx start
